matrix:
    include:
        - dist: xenial

language: rust
rust:
    - nightly
cache:
    - cargo: true

install:
    - sudo apt-get install -y "linux-headers-$(uname -r)" realpath
    - type -p cargo-install-update || cargo install --force cargo-update
    - |
      if type -p cargo-xbuild; then
          cargo install-update -i cargo-xbuild
      else
          cargo install --force cargo-xbuild
      fi
    - rustup component add rust-src rustfmt

script:
    - (cd /tmp; git clone https://github.com/rust-lang/rust-bindgen; cd rust-bindgen; git checkout bb6a1205a0e81271bf90aec33d33e2e3ca0ae7d1)
    - ./tests/run_tests.py
    - |
      for p in . hello-world tests/*; do
        if [ -d "$p" ]; then
          (cd "$p" && cargo fmt --all -- --check) || exit 1
        fi
      done

after_failure:
    - dmesg

notifications:
    email: false
